name: xunyin_app
description: "寻印 - 文化之旅探索 App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 网络请求
  dio: ^5.4.0
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # 路由
  go_router: ^14.0.0
  
  # 本地存储
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # JSON 序列化
  json_annotation: ^4.8.1
  
  # SVG 插画
  flutter_svg: ^2.0.10
  
  # Lottie 动画
  lottie: ^3.1.0
  
  # 图片缓存
  cached_network_image: ^3.3.1
  
  # 图片查看
  photo_view: ^0.15.0
  
  # HTML 渲染
  flutter_widget_from_html: ^0.15.2
  
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  
  # Toast 提示
  fluttertoast: ^8.2.4
  
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  
  # 权限管理
  permission_handler: ^11.3.0
  
  # 截图分享
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^4.0.1
  
  # 地理位置
  geolocator: ^11.0.0
  
  # 高德地图
  amap_flutter_map: ^3.0.0
  amap_flutter_base: ^3.0.0
  amap_flutter_location: ^3.0.0
  image_picker: ^1.2.1
  
  # 音频播放
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  
  # 应用信息
  package_info_plus: ^8.0.0
  
  # 路径获取
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # 代码生成
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/illustrations/
  
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700
